

---

apiVersion: v1
kind: Service
metadata:
  namespace: whoami-argo
  name: whoami-service
  labels:
    app: whoami-app
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: whoami-app


---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: whoami-argo
  name: whoami-deployment
  labels:
    app: whoami-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: whoami-app
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: whoami-app
    spec:
      containers:
      - name: whoami-container
        image: containous/whoami
